version: "3.9"
services:
  web:
    image: zero2prod
    ports:
      - "8000:8000"
  postgres:
    image: postgres:12
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: password
      POSTGRES_DB: postgres
    ports:
      - "5432:5432"